services:
  production:
    container_name: qso-logger-${NAME}
    image: nginx:alpine
    volumes:
      - './build:/build:z'
      - './nginx/default.conf:/etc/nginx/templates/default.conf.template'
    env_file:
      - './.env'
    ports:
      - ${NGINX_PORT}:80
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
